### Define the default configuration files.
defaults:
- data: zarr
- dataloader: native_grid
- datamodule: single
- diagnostics: evaluation
- hardware: example
- graph: multi_scale
- model: graphtransformer
- training: default
- _self_

config_validation: True

### This file is for local experimentation.
# Hardware configuration
hardware:
  paths:
    data: /datasets/
    output: /home/student/anemoi-output/
  files:
    dataset: aifs-ea-an-oper-0001-mars-o48-2010-2022-6h-v1-toy.zarr
  accelerator: auto
  num_nodes: 1
  num_gpus_per_model: 1

# model configuration
model:
  num_channels: 256
  processor:
    num_layers: 8

# Dataloader configuration
dataloader:
  dataset: 
    dataset: ${hardware.paths.data}/${hardware.files.dataset}
    select:  ['z_1000', 'z_500', 'z_700', 'z_300', '2t', 't_850', 'tcw', 'z_250', 'lsm', 'z', 'cp', 'tp', 'cos_latitude', 'cos_longitude', 'sin_latitude', 'sin_longitude', 'cos_julian_day', 'cos_local_time', 'sin_julian_day', 'sin_local_time', 'insolation', 'lsm', 'sdor', 'slor', 'z']
  batch_size:
    training: 8
    validation: 8
  limit_batches:
    training: 100
    validation: 100
training:
  max_steps: 50000
  lr:
    rate: 0.625e-4 #local_lr
    iterations: ${training.max_steps} 
    min: 3e-7 
  variable_groups:
    default: sfc
    pl:
     param: [t, z]
  metrics:
  - z_500
  - t_850

diagnostics:
  plot:
    parameters:
    - z_500
    - t_850
    - 2t
    - tp
  log:
    mlflow:
      system: True
